# .gitlab-ci.yml
image: node:18

# define pipeline stages
stages:
  - git-clone-lambda-code
  - deploy

# install build tools
before_script:
- apt-get update
- apt-get install -y build-essential
- npm install -g serverless

git-clone-lambda-code:
  stage: git-clone-lambda-code
  image: alpine
  before_script:
    - apk add git
  script:
    - git clone --depth=1 -b main https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/serverless4741110/lambdas-src .
    - rm -rf source_code/.git
    - rm LICENSE
    - rm README.md
    - cd src
    - ls
  artifacts:
    paths:
      - src

# run dummy test command
# test:
#   stage: test
#   script:
#     - cd source_code/src
#     - npm run test

deploy_production:
  stage: deploy

  # tag deploy to an environment for tracking
  environment:
    name: production
  script:
  - sls deploy --stage production

  # save build artifacts for publishing
  artifacts:
    paths:
    - .serverless

  # only build when updates are made to "master" branch
  only:
  - main

deploy_staging:
  stage: deploy

  # tag deploy to an environment for tracking
  environment:
    name: staging
  script:
  - yarn run deploy

  # save build artifacts for publishing
  artifacts:
    paths:
    - .serverless

  # only build when updates are made to "staging" branch
  only:
  - staging