service: mimic
frameworkVersion: '3'

custom:
  tableName: 'mimic-sls-${sls:stage}'

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-central-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    DYNAMO_DB_USE_LOCAL: false
    DYNAMO_DB_REGION: eu-central-1
    MIMIC_TABLE: ${self:custom.tableName}

functions:
  mimicListens:
    package:
      patterns:
        - repository/src/**
      individually: true
    handler: repository/src/mimicListens.lambdaHandler
    events:
      - http:
          path: /mimic
          method: POST
  mimicResponse:
    package:
      patterns:
        - ../src/**
      individually: true
    handler: repository/src/mimicResponse.lambdaHandler
    events:
      - http:
          path: /mimic/{id}
          method: GET
          request:
            parameters:
              paths:
                id: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}